people_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: analytics_user
      pass: analytics_pass
      port: 5432
      dbname: people_analytics
      schema: analytics_marts
      threads: 4
